### ISSUE TITLE
Setup Secondary Development Cluster

### ISSUE THREAD

**Issue by Omegaice** [NJCoast/cyberspatial#131]
# VM Requirements
3 Standard CRC VMs with 4GB RAM

# Cluster Creation
### Disable Swap
All machines need their swap partitions disabled. Edit /etc/fstab, comment out the swap partition and restart the machines.

### Install Docker
```
sudo apt-get update
sudo apt-get install -y  apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")  $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
```

### Install Kubeadm
```
sudo apt-get update 
sudo apt-get install -y apt-transport-https
sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
sudo cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
```

### Disable UFW
Required to allow NFS shares to work correctly
```
sudo ufw disable
```

### Login to AWS Docker Repository
Contact jsweet@nd.edu for the command to login to the docker repository.

### Initialize Master
```
# Create Cluster
sudo kubeadm init --pod-network-cidr=10.244.0.0/16

# Copy Configuration
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# Setup Overlay Network
kubectl apply -f https://raw.githubusercontent.com/rbankston/canal/15b94c829ab5c0201ca7ab831da7fe44c2708ac8/k8s-install/1.8/canal.yaml
kubectl apply -f https://raw.githubusercontent.com/rbankston/canal/15b94c829ab5c0201ca7ab831da7fe44c2708ac8/k8s-install/1.8/rbac.yaml

# Allow Port Forwarding (Must be done on every restart)
sudo iptables -P FORWARD ACCEPT
```

### Install NFS
```
sudo apt install nfs-kernel-server
sudo mkdir -p /var/nfs/kubernetes/postgres
sudo mkdir -p /var/nfs/kubernetes/geoserver
sudo chown -R nobody:nogroup /var/nfs/kubernetes/*
sudo cat <<EOF >/etc/exports
/var/nfs/kubernetes/postgres    10.0.0.0/255.0.0.0(rw,sync,no_subtree_check,no_root_squash)
/var/nfs/kubernetes/geoserver   10.0.0.0/255.0.0.0(rw,sync,no_subtree_check)
EOF
sudo systemctl restart nfs-kernel-server
```

## Slaves
Copy the join command from the `kubeadm init` executed earlier and run on each slave. Will also need to install NFS client (`sudo apt install nfs-common`)

# Cyberspatial Installation

## Install HELM
Follow installation guide for helm from https://github.com/kubernetes/helm/blob/ab46779b88971235b05aa197d91b43567068935c/docs/rbac.md#example-service-account-with-cluster-admin-role

## Install nginx ingress
Create values.yaml with the following:
```
controller:
  tolerations: 
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

rbac:
  create: true
```

Then setup nginx ingress with the following command:
```
helm install -f values.yaml --name ingress stable/nginx-ingress
```

### Setup Persistant Volumes
Apply the following YAML but modifying the server parameter for the correct server:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: development-cyberspatial-geoserver
  labels:
    app: development-cyberspatial-geoserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - local_lock=posix
  nfs:
    path: /var/nfs/kubernetes/geoserver
    server: njcoast1.virtual.crc.nd.edu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: development-cyberspatial-geoserver
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: development-cyberspatial-geoserver
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: development-cyberspatial-postgres
  labels:
    app: development-cyberspatial-postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - local_lock=posix
  nfs:
    path: /var/nfs/kubernetes/postgres
    server: njcoast1.virtual.crc.nd.edu
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: development-cyberspatial-postgres
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: development-cyberspatial-postgres
```

### Clone and install Cyberspatial
```
git clone https://github.com/NJCoast/helm
cd helm
helm install -n development -f development-values.yaml cyberspatial
```
development-values.yaml needs to be modified to suit the specific needs of the installation.
